### Numpy 随机数模块
>学习网站：https://docs.scipy.org/doc/

In [2]:
import numpy as np

In [2]:
np.random.randint(0,10),np.random.randint(0,10,10),np.random.randint(0,10,(3,5))

(8,
 array([8, 5, 9, 3, 9, 7, 3, 3, 5, 0]),
 array([[0, 3, 2, 7, 5],
        [8, 4, 3, 9, 2],
        [7, 5, 3, 8, 8]]))

In [5]:
np.random.rand(),np.random.rand(10),np.random.rand(3,5)  #生成 0-1 之间的浮点数，传一个参数表示数量，两个参数生成二维数组

(0.36088738250825514,
 array([0.32993248, 0.57075668, 0.15856436, 0.96924421, 0.39704687,
        0.96389112, 0.81968555, 0.24639458, 0.22684698, 0.461925  ]),
 array([[0.95300901, 0.02568634, 0.72859602, 0.99180387, 0.71920566],
        [0.60760917, 0.38416068, 0.04526444, 0.27084101, 0.24173412],
        [0.6095715 , 0.02949786, 0.62763869, 0.29584962, 0.32532583]]))

In [9]:
np.random.random(),np.random.random(size=(2,3)) # 生成二维数组需要设置size属性，rand不需要

(0.1539250884654283,
 array([[0.07589306, 0.70364901, 0.29195292],
        [0.8796312 , 0.05606473, 0.9847244 ]]))

####  numpy.random.randn()　标准正态分布随机数，参数为size

In [10]:
np.random.randn(2,2)

array([[ 1.27924395, -1.02319602],
       [ 1.31271368, -0.78981474]])

In [4]:
np.random.choice([1,2,3,4,5],5)  # 可以选择多次

array([5, 1, 4, 1, 1])

In [5]:
np.random.uniform(2.0,4.0),np.random.uniform(2.0,4.0,10) # 随机生成随机浮点数

(2.4723716631853705,
 array([2.6611461 , 2.02142101, 3.0171039 , 2.78357495, 2.17224104,
        3.98756352, 2.30966721, 3.80596457, 2.27196084, 3.38475339]))

# pandans学习
> 核心数据分析包

In [6]:
import pandas as pd
import numpy as np

### Series -- 一维数据对象
> Series 是一种类似于一维数组的对象，由一组数据和一组与之相关的数据标签(索引)组成。
> 获取值数组和索引数组：values 属性和 index属性
> Series 比较像列表（数组） 和字典的结合体

In [7]:
pd.Series([2,3,4,5]),pd.Series([2,3,4,5],index =['a','b','c','d'] ),pd.Series(np.arange(10,21))

(0    2
 1    3
 2    4
 3    5
 dtype: int64,
 a    2
 b    3
 c    4
 d    5
 dtype: int64,
 0     10
 1     11
 2     12
 3     13
 4     14
 5     15
 6     16
 7     17
 8     18
 9     19
 10    20
 dtype: int32)

In [8]:
s = pd.Series([2,3,4,5],index =['a','b','c','d'] )
s

a    2
b    3
c    4
d    5
dtype: int64

In [9]:
s['a'],s[0],s*2,s[1:],s[s>3],s['b':'c'] # 标签切片是前后都包含的

(2,
 2,
 a     4
 b     6
 c     8
 d    10
 dtype: int64,
 b    3
 c    4
 d    5
 dtype: int64,
 c    4
 d    5
 dtype: int64,
 b    3
 c    4
 dtype: int64)

In [10]:
s1 = pd.Series({'name':'张三','age':10,'grade':'五年级'})
s1

name      张三
age       10
grade    五年级
dtype: object

In [11]:
'name' in s1

True

In [12]:
s1[['name','grade']] # 花式索引

name      张三
grade    五年级
dtype: object

In [13]:
for i in s1:  # 遍历返回的是值
    print(i)

张三
10
五年级


In [14]:
s1.index,s1.values  # 返回索引和值

(Index(['name', 'age', 'grade'], dtype='object'),
 array(['张三', 10, '五年级'], dtype=object))

### 整数索引

In [15]:
sr = pd.Series(np.arange(20))

In [16]:
sr2 = sr[10:]
sr2

10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int32

In [17]:
sr2.loc[10] # 中括号里的值强制解析为标签，返回10，索引，切片，花式索引都支持

10

In [18]:
sr2.iloc[0] # 中括号里的值强制解析为小标索引，返回10

10

### 数据对齐
> pandas 在进行两个Series 对象的运算时，会按索引(标签)进行对齐然后计算

In [19]:
sr1 = pd.Series([12,23,34],index = ['c','a','d'])
sr2 = pd.Series([11,20,10],index = ['d','c','a'])
sr1+sr2

a    33
c    32
d    45
dtype: int64

In [20]:
sr1 = pd.Series([12,23,34],index = ['c','a','d'])
sr2 = pd.Series([11,20,10,21],index = ['d','c','a','b'])
sr1+sr2  # numpy不支持不一样大小的数组相加，但是pandas支持，如果一个Series中不包含某个标签的值，则其值会默认填充NaN

a    33.0
b     NaN
c    32.0
d    45.0
dtype: float64

### 灵活的算术运算,add,sub,div,mul
>可以自定义默认填充值

In [21]:
sr1.add(sr2),sr1.add(sr2,fill_value = 0)

(a    33.0
 b     NaN
 c    32.0
 d    45.0
 dtype: float64,
 a    33.0
 b    21.0
 c    32.0
 d    45.0
 dtype: float64)

### 缺失值的处理
> 删除缺失值与或填充缺失值

In [22]:
sr = sr1+ sr2
sr,sr.isnull() # 是NaN将会返回True

(a    33.0
 b     NaN
 c    32.0
 d    45.0
 dtype: float64,
 a    False
 b     True
 c    False
 d    False
 dtype: bool)

In [23]:
sr = sr1+ sr2
sr,sr.notnull() # 不是NaN将会返回True

(a    33.0
 b     NaN
 c    32.0
 d    45.0
 dtype: float64,
 a     True
 b    False
 c     True
 d     True
 dtype: bool)

In [24]:
sr[sr.notnull()] # 布尔索引过滤掉NaN数据

a    33.0
c    32.0
d    45.0
dtype: float64

In [25]:
sr.dropna() # 直接去去掉NaN行数据

a    33.0
c    32.0
d    45.0
dtype: float64

In [26]:
sr,sr.fillna(0)

(a    33.0
 b     NaN
 c    32.0
 d    45.0
 dtype: float64,
 a    33.0
 b     0.0
 c    32.0
 d    45.0
 dtype: float64)

In [27]:
sr,sr.mean()#计算平局值会跳过NaN数据

(a    33.0
 b     NaN
 c    32.0
 d    45.0
 dtype: float64,
 36.666666666666664)

### DataFrame --二维数据
>DataFrame 是一个表格型的数据结构，含有一组有序的列。DataFrame可以被看做是由Series 组成的字典，并且共用一个索引。

In [28]:
pd.DataFrame({'one':[1,2,3],'two':[4,5,6]})

one  two
0    1    4
1    2    5
2    3    6

In [29]:
pd.DataFrame({'one':pd.Series([1,2,3],index=list('abc')),'two':pd.Series([4,5,6],index=list('abc'))})

one  two
a    1    4
b    2    5
c    3    6

In [30]:
df = _

In [31]:
ls

 驱动器 C 中的卷是 OS
 卷的序列号是 9077-D952

 C:\Users\mx\Documents\Python学习 的目录

2020/11/20  11:59    <DIR>          .
2020/11/20  11:59    <DIR>          ..
2020/11/19  17:40    <DIR>          .ipynb_checkpoints
2020/11/20  11:56                31 df.csv
2020/11/19  18:21            98,488 matplotlib学习笔记.ipynb
2020/11/19  15:54                68 na_values.csv
2020/11/19  15:46                37 no_header.csv
2020/11/20  11:59           143,346 numpy_pandans学习笔记2.ipynb
2020/11/19  15:30            92,262 price.csv
2019/10/12  17:43             4,255 pygame_study.ipynb
2019/10/12  13:54             3,326 python——OS模块学习.ipynb
2020/11/19  09:24    <DIR>          reneme_video
2020/11/19  10:51                24 test.csv
2019/10/05  18:37            14,108 正则表达式学习.ipynb
              10 个文件        355,945 字节
               4 个目录 27,530,825,728 可用字节


In [32]:
df.to_csv('df.csv') # 保存到csv文件

In [33]:
ls

 驱动器 C 中的卷是 OS
 卷的序列号是 9077-D952

 C:\Users\mx\Documents\Python学习 的目录

2020/11/20  11:59    <DIR>          .
2020/11/20  11:59    <DIR>          ..
2020/11/19  17:40    <DIR>          .ipynb_checkpoints
2020/11/20  12:14                31 df.csv
2020/11/19  18:21            98,488 matplotlib学习笔记.ipynb
2020/11/19  15:54                68 na_values.csv
2020/11/19  15:46                37 no_header.csv
2020/11/20  11:59           143,346 numpy_pandans学习笔记2.ipynb
2020/11/19  15:30            92,262 price.csv
2019/10/12  17:43             4,255 pygame_study.ipynb
2019/10/12  13:54             3,326 python——OS模块学习.ipynb
2020/11/19  09:24    <DIR>          reneme_video
2020/11/19  10:51                24 test.csv
2019/10/05  18:37            14,108 正则表达式学习.ipynb
              10 个文件        355,945 字节
               4 个目录 27,530,825,728 可用字节


In [34]:
pd.read_csv('test.csv') # 读取CSV文件

one  two
0    1    4
1    2    5
2    3    6

### DataFrame常用属性
>index---获取索引
>T  ----  转置
>values  --  返回值(二维数组)
>columns --  列索引
>describe  -- 获取快速统计

In [35]:
df =_

In [36]:
df,df.index,df.values,df.columns,df.describe(),df.T

(   one  two
 0    1    4
 1    2    5
 2    3    6,
 RangeIndex(start=0, stop=3, step=1),
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int64),
 Index(['one', 'two'], dtype='object'),
        one  two
 count  3.0  3.0
 mean   2.0  5.0
 std    1.0  1.0
 min    1.0  4.0
 25%    1.5  4.5
 50%    2.0  5.0
 75%    2.5  5.5
 max    3.0  6.0,
      0  1  2
 one  1  2  3
 two  4  5  6)

In [37]:
df.index= ['a','b','c']
df

one  two
a    1    4
b    2    5
c    3    6

In [38]:
df['one']['a'] # 先选列再选行,这种方式不建议

1

In [39]:
df.loc['a','one']  # 通过标签选择，行,列，这种方法更建议使用

1

In [40]:
df['one'],df.loc['a']

(a    1
 b    2
 c    3
 Name: one, dtype: int64,
 one    1
 two    4
 Name: a, dtype: int64)

In [41]:
df.loc[['a','c'],'one']

a    1
c    3
Name: one, dtype: int64

### DataFrame 数据对齐与缺失数据

In [42]:
df

one  two
a    1    4
b    2    5
c    3    6

In [43]:
df2 = pd.DataFrame({'two':[11,22,33,44],'three':[4,4,6,8]},index=list('abcd'))
df2

two  three
a   11      4
b   22      4
c   33      6
d   44      8

In [44]:
df3 = df+df2
df3

one  three   two
a  NaN    NaN  15.0
b  NaN    NaN  27.0
c  NaN    NaN  39.0
d  NaN    NaN   NaN

In [45]:
df3.fillna(0) # 将NaN填充一个值

one  three   two
a  0.0    0.0  15.0
b  0.0    0.0  27.0
c  0.0    0.0  39.0
d  0.0    0.0   0.0

In [46]:
df3.dropna() # 如果一行中存在NaN，则改行都会被删除

Empty DataFrame
Columns: [one, three, two]
Index: []

In [47]:
df3.dropna(how='all') # 只有一行全是NaN的时候，该行才会被删除

one  three   two
a  NaN    NaN  15.0
b  NaN    NaN  27.0
c  NaN    NaN  39.0

In [48]:
df3

one  three   two
a  NaN    NaN  15.0
b  NaN    NaN  27.0
c  NaN    NaN  39.0
d  NaN    NaN   NaN

In [49]:
df3['one'] = [1,2,3,4]

In [50]:
df3

one  three   two
a    1    NaN  15.0
b    2    NaN  27.0
c    3    NaN  39.0
d    4    NaN   NaN

In [51]:
df3.loc['a':'c','three'] = [45,56,67]
df3

one  three   two
a    1   45.0  15.0
b    2   56.0  27.0
c    3   67.0  39.0
d    4    NaN   NaN

In [52]:
df3.dropna(axis = 1) #  制定轴，axis = 1 列方向

one
a    1
b    2
c    3
d    4

In [53]:
df3.isnull()

one  three    two
a  False  False  False
b  False  False  False
c  False  False  False
d  False   True   True

### pandas 常用函数

In [54]:
df

one  two
a    1    4
b    2    5
c    3    6

In [55]:
df.mean() # 求每一列的平均值，会自动跳过NaN

one    2.0
two    5.0
dtype: float64

In [56]:
df.mean(axis = 1)  # 按行求平均值

a    2.5
b    3.5
c    4.5
dtype: float64

In [57]:
df.sum() # 默认按列求和

one     6
two    15
dtype: int64

In [58]:
df.sum(axis = 1)

a    5
b    7
c    9
dtype: int64

In [59]:
df

one  two
a    1    4
b    2    5
c    3    6

In [60]:
df.loc['d'] = [0,3]

In [61]:
df

one  two
a    1    4
b    2    5
c    3    6
d    0    3

###  按值排序

In [62]:
df.sort_values(by='one') # 按列排序，通过by制定列，默认升序排列

one  two
d    0    3
a    1    4
b    2    5
c    3    6

In [63]:
df.sort_values(by='two',ascending=False) # 降序排列

one  two
c    3    6
b    2    5
a    1    4
d    0    3

In [64]:
df.sort_values(axis=1,by='a',ascending=False) # 按行排序

two  one
a    4    1
b    5    2
c    6    3
d    3    0

In [65]:
df.sort_values(axis=1,by='b',ascending=True) # 按行排序

one  two
a    1    4
b    2    5
c    3    6
d    0    3

In [66]:
df

one  two
a    1    4
b    2    5
c    3    6
d    0    3

In [67]:
df.loc[:,'three'] = [1,9,3,3]

In [68]:
df

one  two  three
a    1    4      1
b    2    5      9
c    3    6      3
d    0    3      3

In [69]:
df3

one  three   two
a    1   45.0  15.0
b    2   56.0  27.0
c    3   67.0  39.0
d    4    NaN   NaN

In [70]:
df3.sort_values(by='two',ascending=False)  #排序的时候，有NaN的一行总是放在最后

one  three   two
c    3   67.0  39.0
b    2   56.0  27.0
a    1   45.0  15.0
d    4    NaN   NaN

In [71]:
df3.sort_values(by='two',ascending=True)  

one  three   two
a    1   45.0  15.0
b    2   56.0  27.0
c    3   67.0  39.0
d    4    NaN   NaN

### 按索引(标签)排序

In [72]:
df

one  two  three
a    1    4      1
b    2    5      9
c    3    6      3
d    0    3      3

In [73]:
df.sort_index(ascending=False)  # 默认按行标签排序

one  two  three
d    0    3      3
c    3    6      3
b    2    5      9
a    1    4      1

In [74]:
df.sort_index(ascending=False,axis = 1)

two  three  one
a    4      1    1
b    5      9    2
c    6      3    3
d    3      3    0

### pandas - 时间对象处理

In [75]:
from datetime import datetime

In [76]:
datetime.strptime('2020-11-18','%Y-%m-%d')

datetime.datetime(2020, 11, 18, 0, 0)

In [77]:
import dateutil   # 安装pandas自动安装的一个库

In [78]:
dateutil.parser.parse('2020-11-18'),dateutil.parser.parse('2020/11/18'),dateutil.parser.parse('2020-Jan-18')#自动解析成日期时间对象

(datetime.datetime(2020, 11, 18, 0, 0),
 datetime.datetime(2020, 11, 18, 0, 0),
 datetime.datetime(2020, 1, 18, 0, 0))

In [79]:
pd.to_datetime(['2020-11-18','2020/11/18','2020-Feb-18']) # 批量解析时间日期字符串

DatetimeIndex(['2020-11-18', '2020-11-18', '2020-02-18'], dtype='datetime64[ns]', freq=None)

In [80]:
pd.date_range('2020-01-01','2020-11-11') # 制定开始与结束日期

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-11-02', '2020-11-03', '2020-11-04', '2020-11-05',
               '2020-11-06', '2020-11-07', '2020-11-08', '2020-11-09',
               '2020-11-10', '2020-11-11'],
              dtype='datetime64[ns]', length=316, freq='D')

In [81]:
pd.date_range('2020-01-01',periods=30)  #制定起始日期与长度，默认按天递增即freq属性

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30'],
              dtype='datetime64[ns]', freq='D')

In [82]:
pd.date_range('2020-01-01',periods=30,freq='H')  #按小时递增

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00', '2020-01-01 07:00:00',
               '2020-01-01 08:00:00', '2020-01-01 09:00:00',
               '2020-01-01 10:00:00', '2020-01-01 11:00:00',
               '2020-01-01 12:00:00', '2020-01-01 13:00:00',
               '2020-01-01 14:00:00', '2020-01-01 15:00:00',
               '2020-01-01 16:00:00', '2020-01-01 17:00:00',
               '2020-01-01 18:00:00', '2020-01-01 19:00:00',
               '2020-01-01 20:00:00', '2020-01-01 21:00:00',
               '2020-01-01 22:00:00', '2020-01-01 23:00:00',
               '2020-01-02 00:00:00', '2020-01-02 01:00:00',
               '2020-01-02 02:00:00', '2020-01-02 03:00:00',
               '2020-01-02 04:00:00', '2020-01-02 05:00:00'],
              dtype='datetime64[ns]', freq='H')

In [83]:
pd.date_range('2020-01-01',periods=30,freq='W')  #按周递增，每周日

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02', '2020-02-09', '2020-02-16', '2020-02-23',
               '2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22',
               '2020-03-29', '2020-04-05', '2020-04-12', '2020-04-19',
               '2020-04-26', '2020-05-03', '2020-05-10', '2020-05-17',
               '2020-05-24', '2020-05-31', '2020-06-07', '2020-06-14',
               '2020-06-21', '2020-06-28', '2020-07-05', '2020-07-12',
               '2020-07-19', '2020-07-26'],
              dtype='datetime64[ns]', freq='W-SUN')

In [84]:
pd.date_range('2020-01-01',periods=30,freq='W-MON')  #按周递增，每周一

DatetimeIndex(['2020-01-06', '2020-01-13', '2020-01-20', '2020-01-27',
               '2020-02-03', '2020-02-10', '2020-02-17', '2020-02-24',
               '2020-03-02', '2020-03-09', '2020-03-16', '2020-03-23',
               '2020-03-30', '2020-04-06', '2020-04-13', '2020-04-20',
               '2020-04-27', '2020-05-04', '2020-05-11', '2020-05-18',
               '2020-05-25', '2020-06-01', '2020-06-08', '2020-06-15',
               '2020-06-22', '2020-06-29', '2020-07-06', '2020-07-13',
               '2020-07-20', '2020-07-27'],
              dtype='datetime64[ns]', freq='W-MON')

In [85]:
pd.date_range('2020-01-01',periods=30,freq='B')  #按工作日递增

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
               '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
               '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-03',
               '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07',
               '2020-02-10', '2020-02-11'],
              dtype='datetime64[ns]', freq='B')

In [86]:
dt = pd.date_range('2020-01-01',periods=30,freq='B')  #按工作日递增
dt[0].to_pydatetime()  # 转成python 日期时间对象

datetime.datetime(2020, 1, 1, 0, 0)

In [87]:
pd.date_range('2020-01-01',periods=30,freq='1H20min')  #按工作日递增

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:20:00',
               '2020-01-01 02:40:00', '2020-01-01 04:00:00',
               '2020-01-01 05:20:00', '2020-01-01 06:40:00',
               '2020-01-01 08:00:00', '2020-01-01 09:20:00',
               '2020-01-01 10:40:00', '2020-01-01 12:00:00',
               '2020-01-01 13:20:00', '2020-01-01 14:40:00',
               '2020-01-01 16:00:00', '2020-01-01 17:20:00',
               '2020-01-01 18:40:00', '2020-01-01 20:00:00',
               '2020-01-01 21:20:00', '2020-01-01 22:40:00',
               '2020-01-02 00:00:00', '2020-01-02 01:20:00',
               '2020-01-02 02:40:00', '2020-01-02 04:00:00',
               '2020-01-02 05:20:00', '2020-01-02 06:40:00',
               '2020-01-02 08:00:00', '2020-01-02 09:20:00',
               '2020-01-02 10:40:00', '2020-01-02 12:00:00',
               '2020-01-02 13:20:00', '2020-01-02 14:40:00'],
              dtype='datetime64[ns]', freq='80T')

#### pandas -- 时间序列
> 时间序列就是以时间对象为索引的Series 或DataFrame
>datetime对象作为索引时，是存储在DatetimeIndex对象中的

>时间序列的特殊功能：
1.传入'年' 或 ‘年月’作为切片方式
2.传入日期范围作为切片方式
3.丰富的函数支持：resample(),truncate();...

In [88]:
sr = pd.Series(np.arange(1000),index=pd.date_range('2018-10-1',periods=1000))
sr

2018-10-01      0
2018-10-02      1
2018-10-03      2
2018-10-04      3
2018-10-05      4
             ... 
2021-06-22    995
2021-06-23    996
2021-06-24    997
2021-06-25    998
2021-06-26    999
Freq: D, Length: 1000, dtype: int32

In [89]:
sr.index

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10',
               ...
               '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20',
               '2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24',
               '2021-06-25', '2021-06-26'],
              dtype='datetime64[ns]', length=1000, freq='D')

In [90]:
sr['2018-11'] # 只返回2018年11月份的数据

2018-11-01    31
2018-11-02    32
2018-11-03    33
2018-11-04    34
2018-11-05    35
2018-11-06    36
2018-11-07    37
2018-11-08    38
2018-11-09    39
2018-11-10    40
2018-11-11    41
2018-11-12    42
2018-11-13    43
2018-11-14    44
2018-11-15    45
2018-11-16    46
2018-11-17    47
2018-11-18    48
2018-11-19    49
2018-11-20    50
2018-11-21    51
2018-11-22    52
2018-11-23    53
2018-11-24    54
2018-11-25    55
2018-11-26    56
2018-11-27    57
2018-11-28    58
2018-11-29    59
2018-11-30    60
Freq: D, dtype: int32

In [91]:
sr['2018-12':'2019-02'] # 时间切片

2018-12-01     61
2018-12-02     62
2018-12-03     63
2018-12-04     64
2018-12-05     65
             ... 
2019-02-24    146
2019-02-25    147
2019-02-26    148
2019-02-27    149
2019-02-28    150
Freq: D, Length: 90, dtype: int32

In [92]:
sr.resample('M').sum() # 每月取样，求和

2018-10-31      465
2018-11-30     1365
2018-12-31     2356
2019-01-31     3317
2019-02-28     3822
2019-03-31     5146
2019-04-30     5895
2019-05-31     7037
2019-06-30     7725
2019-07-31     8928
2019-08-31     9889
2019-09-30    10485
2019-10-31    11780
2019-11-30    12315
2019-12-31    13671
2020-01-31    14632
2020-02-29    14558
2020-03-31    16492
2020-04-30    16875
2020-05-31    18383
2020-06-30    18705
2020-07-31    20274
2020-08-31    21235
2020-09-30    21465
2020-10-31    23126
2020-11-30    23295
2020-12-31    25017
2021-01-31    25978
2021-02-28    24290
2021-03-31    27807
2021-04-30    27825
2021-05-31    29698
2021-06-30    25649
Freq: M, dtype: int32

In [93]:
sr.resample('W').mean()  #平均值

2018-10-07      3.0
2018-10-14     10.0
2018-10-21     17.0
2018-10-28     24.0
2018-11-04     31.0
              ...  
2021-05-30    969.0
2021-06-06    976.0
2021-06-13    983.0
2021-06-20    990.0
2021-06-27    996.5
Freq: W-SUN, Length: 143, dtype: float64

###  文件处理
>常用格式：CSV （以某间隔符分割数据，一般用用逗号）
pandas 读取文件：文件名，URL，文件对象

>read_csv   默认分隔符是逗号

>read_table  默认分隔符是制表符

In [94]:
pd.read_csv('price.csv')

Unnamed: 0  tradeDate  preClosePrice  actPreClosePrice  openPrice  \
0              0   2015/1/5          15.84             15.84      15.99   
1              1   2015/1/6          16.02             16.02      15.85   
2              2   2015/1/7          15.78             15.78      15.56   
3              3   2015/1/8          15.48             15.48      15.50   
4              4   2015/1/9          14.96             14.96      14.90   
...          ...        ...            ...               ...        ...   
1397        1397  2020/9/24          15.63             15.63      15.59   
1398        1398  2020/9/25          15.12             15.12      15.20   
1399        1399  2020/9/28          15.19             15.19      15.19   
1400        1400  2020/9/29          15.31             15.31      15.39   
1401        1401  2020/9/30          14.80             14.80      14.80   

      highestPrice  lowestPrice  closePrice  dealAmount   marketValue  isOpen  
0            16.28        15.60       16.02       92478  1.830000e+11       1  
1            16.39        15.55       15.78       80325  1.800000e+11       1  
2            15.83        15.30       15.48       72697  1.770000e+11       1  
3            15.57        14.90       14.96       68734  1.710000e+11       1  
4            15.87        14.71       15.08       99882  1.720000e+11       1  
...            ...          ...         ...         ...           ...     ...  
1397         15.61        15.12       15.12       71693  2.930000e+11       1  
1398         15.31        15.11       15.19       38187  2.950000e+11       1  
1399         15.37        14.98       15.31       38648  2.970000e+11       1  
1400         15.41        14.76       14.80       72662  2.870000e+11       1  
1401         15.27        14.80       15.17       71561  2.940000e+11       1  

[1402 rows x 11 columns]

In [95]:
df = pd.read_csv('price.csv',index_col='tradeDate') # 指定一列作为索引(标签)，这里读取的日期还是字符串
df

Unnamed: 0  preClosePrice  actPreClosePrice  openPrice  \
tradeDate                                                           
2015/1/5            0          15.84             15.84      15.99   
2015/1/6            1          16.02             16.02      15.85   
2015/1/7            2          15.78             15.78      15.56   
2015/1/8            3          15.48             15.48      15.50   
2015/1/9            4          14.96             14.96      14.90   
...               ...            ...               ...        ...   
2020/9/24        1397          15.63             15.63      15.59   
2020/9/25        1398          15.12             15.12      15.20   
2020/9/28        1399          15.19             15.19      15.19   
2020/9/29        1400          15.31             15.31      15.39   
2020/9/30        1401          14.80             14.80      14.80   

           highestPrice  lowestPrice  closePrice  dealAmount   marketValue  \
tradeDate                                                                    
2015/1/5          16.28        15.60       16.02       92478  1.830000e+11   
2015/1/6          16.39        15.55       15.78       80325  1.800000e+11   
2015/1/7          15.83        15.30       15.48       72697  1.770000e+11   
2015/1/8          15.57        14.90       14.96       68734  1.710000e+11   
2015/1/9          15.87        14.71       15.08       99882  1.720000e+11   
...                 ...          ...         ...         ...           ...   
2020/9/24         15.61        15.12       15.12       71693  2.930000e+11   
2020/9/25         15.31        15.11       15.19       38187  2.950000e+11   
2020/9/28         15.37        14.98       15.31       38648  2.970000e+11   
2020/9/29         15.41        14.76       14.80       72662  2.870000e+11   
2020/9/30         15.27        14.80       15.17       71561  2.940000e+11   

           isOpen  
tradeDate          
2015/1/5        1  
2015/1/6        1  
2015/1/7        1  
2015/1/8        1  
2015/1/9        1  
...           ...  
2020/9/24       1  
2020/9/25       1  
2020/9/28       1  
2020/9/29       1  
2020/9/30       1  

[1402 rows x 10 columns]

In [96]:
df.index

Index(['2015/1/5', '2015/1/6', '2015/1/7', '2015/1/8', '2015/1/9', '2015/1/12',
       '2015/1/13', '2015/1/14', '2015/1/15', '2015/1/16',
       ...
       '2020/9/17', '2020/9/18', '2020/9/21', '2020/9/22', '2020/9/23',
       '2020/9/24', '2020/9/25', '2020/9/28', '2020/9/29', '2020/9/30'],
      dtype='object', name='tradeDate', length=1402)

In [97]:
type(df.index[0])

str

In [98]:
df = pd.read_csv('price.csv',index_col='tradeDate',parse_dates = True) # 把能转换成日期时间对象的字符串都进行转换
df

Unnamed: 0  preClosePrice  actPreClosePrice  openPrice  \
tradeDate                                                            
2015-01-05           0          15.84             15.84      15.99   
2015-01-06           1          16.02             16.02      15.85   
2015-01-07           2          15.78             15.78      15.56   
2015-01-08           3          15.48             15.48      15.50   
2015-01-09           4          14.96             14.96      14.90   
...                ...            ...               ...        ...   
2020-09-24        1397          15.63             15.63      15.59   
2020-09-25        1398          15.12             15.12      15.20   
2020-09-28        1399          15.19             15.19      15.19   
2020-09-29        1400          15.31             15.31      15.39   
2020-09-30        1401          14.80             14.80      14.80   

            highestPrice  lowestPrice  closePrice  dealAmount   marketValue  \
tradeDate                                                                     
2015-01-05         16.28        15.60       16.02       92478  1.830000e+11   
2015-01-06         16.39        15.55       15.78       80325  1.800000e+11   
2015-01-07         15.83        15.30       15.48       72697  1.770000e+11   
2015-01-08         15.57        14.90       14.96       68734  1.710000e+11   
2015-01-09         15.87        14.71       15.08       99882  1.720000e+11   
...                  ...          ...         ...         ...           ...   
2020-09-24         15.61        15.12       15.12       71693  2.930000e+11   
2020-09-25         15.31        15.11       15.19       38187  2.950000e+11   
2020-09-28         15.37        14.98       15.31       38648  2.970000e+11   
2020-09-29         15.41        14.76       14.80       72662  2.870000e+11   
2020-09-30         15.27        14.80       15.17       71561  2.940000e+11   

            isOpen  
tradeDate           
2015-01-05       1  
2015-01-06       1  
2015-01-07       1  
2015-01-08       1  
2015-01-09       1  
...            ...  
2020-09-24       1  
2020-09-25       1  
2020-09-28       1  
2020-09-29       1  
2020-09-30       1  

[1402 rows x 10 columns]

In [99]:
df.index

DatetimeIndex(['2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
               '2015-01-09', '2015-01-12', '2015-01-13', '2015-01-14',
               '2015-01-15', '2015-01-16',
               ...
               '2020-09-17', '2020-09-18', '2020-09-21', '2020-09-22',
               '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-28',
               '2020-09-29', '2020-09-30'],
              dtype='datetime64[ns]', name='tradeDate', length=1402, freq=None)

In [100]:
df = pd.read_csv('price.csv',index_col='tradeDate',parse_dates = ['tradeDate']) # 指定某一列解析成时间日期对象
df

Unnamed: 0  preClosePrice  actPreClosePrice  openPrice  \
tradeDate                                                            
2015-01-05           0          15.84             15.84      15.99   
2015-01-06           1          16.02             16.02      15.85   
2015-01-07           2          15.78             15.78      15.56   
2015-01-08           3          15.48             15.48      15.50   
2015-01-09           4          14.96             14.96      14.90   
...                ...            ...               ...        ...   
2020-09-24        1397          15.63             15.63      15.59   
2020-09-25        1398          15.12             15.12      15.20   
2020-09-28        1399          15.19             15.19      15.19   
2020-09-29        1400          15.31             15.31      15.39   
2020-09-30        1401          14.80             14.80      14.80   

            highestPrice  lowestPrice  closePrice  dealAmount   marketValue  \
tradeDate                                                                     
2015-01-05         16.28        15.60       16.02       92478  1.830000e+11   
2015-01-06         16.39        15.55       15.78       80325  1.800000e+11   
2015-01-07         15.83        15.30       15.48       72697  1.770000e+11   
2015-01-08         15.57        14.90       14.96       68734  1.710000e+11   
2015-01-09         15.87        14.71       15.08       99882  1.720000e+11   
...                  ...          ...         ...         ...           ...   
2020-09-24         15.61        15.12       15.12       71693  2.930000e+11   
2020-09-25         15.31        15.11       15.19       38187  2.950000e+11   
2020-09-28         15.37        14.98       15.31       38648  2.970000e+11   
2020-09-29         15.41        14.76       14.80       72662  2.870000e+11   
2020-09-30         15.27        14.80       15.17       71561  2.940000e+11   

            isOpen  
tradeDate           
2015-01-05       1  
2015-01-06       1  
2015-01-07       1  
2015-01-08       1  
2015-01-09       1  
...            ...  
2020-09-24       1  
2020-09-25       1  
2020-09-28       1  
2020-09-29       1  
2020-09-30       1  

[1402 rows x 10 columns]

In [101]:
df.index

DatetimeIndex(['2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
               '2015-01-09', '2015-01-12', '2015-01-13', '2015-01-14',
               '2015-01-15', '2015-01-16',
               ...
               '2020-09-17', '2020-09-18', '2020-09-21', '2020-09-22',
               '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-28',
               '2020-09-29', '2020-09-30'],
              dtype='datetime64[ns]', name='tradeDate', length=1402, freq=None)

In [102]:
df2 = pd.read_csv('no_header.csv') # 直接读取会将第一行数据作为列索引
df2

Jack  100
0    Tom   80
1  Herry   99
2   Musk   63

In [103]:
pd.read_csv('no_header.csv',header=None)

0    1
0   Jack  100
1    Tom   80
2  Herry   99
3   Musk   63

In [104]:
pd.read_csv('no_header.csv',names=['name','scores'])

name  scores
0   Jack     100
1    Tom      80
2  Herry      99
3   Musk      63

### 自定哪些值作为缺省值(NaN)

In [105]:
df3 = pd.read_csv('na_values.csv')
df3

name score   age
0   Jack   100  none
1    Tom    80    10
2  Herry   NAN    12
3   Musk    63    13

In [106]:
df3['score']  # 数据类型变成了object,NAN被解析成了字符串

0    100
1     80
2    NAN
3     63
Name: score, dtype: object

In [107]:
df3['age']

0    none
1      10
2      12
3      13
Name: age, dtype: object

In [108]:
df3 = pd.read_csv('na_values.csv',na_values=['NAN','none'])
df3

name  score   age
0   Jack  100.0   NaN
1    Tom   80.0  10.0
2  Herry    NaN  12.0
3   Musk   63.0  13.0

In [109]:
df3['age']  #这个时候数据类型就是浮点数了

0     NaN
1    10.0
2    12.0
3    13.0
Name: age, dtype: float64

In [110]:
df3['score']

0    100.0
1     80.0
2      NaN
3     63.0
Name: score, dtype: float64

### 写到CSV文件中
>to_csv函数主要参数：

>sep -- 指定分隔符    na_rep  --- 指定缺失值转换的字符串(需要将NaN转换成字符串，写入csv文件中)，默认为空字符串

> header = False  -- 不输出列名 一行

> index = False  -- 不输出行索引那一列

> columns -- 指定输出的列，初入列表

### 读取Excel文件的时候，需要安装一个库 xlrd

In [1]:
# pip install xlrd
import pandas as pd

In [2]:
df = pd.read_excel('test.xlsx',sheet_name='Sheet1')
df  #因为该表格没有表头，所有默认第一行会被读取为表头

1     78      5678
0     2   789    8900
1     3   878  234567

In [3]:
df = pd.read_excel('test.xlsx',sheet_name='Sheet1',names=['月份','销售额','总销售额'])
df # 同样会缺失第一行数据

月份  销售额    总销售额
0   2  789    8900
1   3  878  234567

In [4]:
df = pd.read_excel('test.xlsx',sheet_name='Sheet1',names=['月份','销售额','总销售额'],header = None)
df # 没有表头，将header设置为None

月份  销售额    总销售额
0   1   78    5678
1   2  789    8900
2   3  878  234567

### pandas.read_excel()
* dtype:使用字典设置列的类型
* str -> object
* string -> 常规的字符串
* category -> 分类，类似于枚举类型
* period -> 时间周期(年/月/日)

In [5]:
df = pd.read_excel('test.xlsx',sheet_name='Sheet2')
df 

月份  销售额    总销售额  商品年份       上架日期     在售
0   1   78    5678  2019 2018-01-01   True
1   2  789    8900  2020 2019-03-03  False
2   3  878  234567  2018 2010-01-01   True

In [6]:
df.dtypes

月份               int64
销售额              int64
总销售额             int64
商品年份             int64
上架日期    datetime64[ns]
在售                bool
dtype: object

#### 读取Excel的时候，设置一下数据类型

In [7]:
df = pd.read_excel('test.xlsx',sheet_name='Sheet2',dtype={'月份':'string'})
df 

月份  销售额    总销售额  商品年份       上架日期     在售
0  1   78    5678  2019 2018-01-01   True
1  2  789    8900  2020 2019-03-03  False
2  3  878  234567  2018 2010-01-01   True

In [8]:
df.dtypes

月份              string
销售额              int64
总销售额             int64
商品年份             int64
上架日期    datetime64[ns]
在售                bool
dtype: object

### 读取之后，修改数据类型

In [9]:
df = pd.read_excel('test.xlsx',sheet_name='Sheet2')
df 

月份  销售额    总销售额  商品年份       上架日期     在售
0   1   78    5678  2019 2018-01-01   True
1   2  789    8900  2020 2019-03-03  False
2   3  878  234567  2018 2010-01-01   True

In [10]:
df.dtypes

月份               int64
销售额              int64
总销售额             int64
商品年份             int64
上架日期    datetime64[ns]
在售                bool
dtype: object

In [12]:
# 目标：将月份从int64修改成字符串
df['月份'] = df['月份'].astype('string')
df.dtypes

月份              string
销售额              int64
总销售额             int64
商品年份             int64
上架日期    datetime64[ns]
在售                bool
dtype: object

### 中文日期
> Excel表格中如果日期是这种格式的：2020年1月1日
> 只要在Excel中它的格式是日期，那么pandas也是可以正确解析的

In [34]:
df2 = pd.read_excel('test.xlsx',sheet_name='Sheet3',parse_dates=['日期','日期2'],index_col='日期')
df2

商品    售价        日期2
日期                            
2020-01-01  A  3444 2010-08-09
2020-03-08  B   555 2020-01-08

In [35]:
df2.index

DatetimeIndex(['2020-01-01', '2020-03-08'], dtype='datetime64[ns]', name='日期', freq=None)

### 把多列解析成一个日期
* 例如 年  月  日  写在三列上

In [36]:
df2 = pd.read_excel('test.xlsx',sheet_name='Sheet4',parse_dates=[['年','月','日'],'日期2'])
df2

年_月_日 商品    售价        日期2
0 2020-01-06  A  3444 2010-08-09
1 2019-03-08  B   555 2020-01-08

In [50]:
# 队合并后的列标签重命名
df2 = pd.read_excel('test.xlsx',sheet_name='Sheet4',parse_dates={'日期':['年','月','日']})
df2

日期 商品    售价        日期2
0 2020-01-06  A  3444 2010-08-09
1 2019-03-08  B   555 2020-01-08

In [46]:
df2.dtypes

日期     datetime64[ns]
商品             object
售价              int64
日期2    datetime64[ns]
dtype: object

In [51]:
# 队合并后的列标签重命名2
df2 = pd.read_excel('test.xlsx',sheet_name='Sheet4',parse_dates=[['年','月','日'],'日期2'])
df2

年_月_日 商品    售价        日期2
0 2020-01-06  A  3444 2010-08-09
1 2019-03-08  B   555 2020-01-08

In [59]:
df2.rename(columns={'年_月_日':'日期'},inplace=True)
df2

日期 商品    售价        日期2
0 2020-01-06  A  3444 2010-08-09
1 2019-03-08  B   555 2020-01-08

## converter 参数
> 可以传入一个函数，队读取的数据预处理
* 感觉作用不大，完全可以读取之后再处理

In [60]:
df3 = pd.read_excel('test.xlsx',sheet_name='Sheet6')
df3

年        月  日
0  2020      \n1  6
1  2019  \t\r\n3  8

In [66]:
df3 = pd.read_excel('test.xlsx',sheet_name='Sheet6', converters= {'月':lambda x:x*2})
df3

年   月  日
0  2020   8  6
1  2019  10  8

In [67]:
df3.dtypes

年    int64
月    int64
日    int64
dtype: object